### PR TITLE
monitoring: change K8s namespace to `metalk8s-monitoring`

### PR DESCRIPTION
**Pull request by NicolasT**
Fixes: #1540
See: https://github.com/scality/metalk8s/issues/1540

### CODE REVIEW

**Comment by NicolasT** [comment]
@bert-e status

**Comment by NicolasT** [comment]
@bert-e reset

**Comment by NicolasT** [comment]
@bert-e status

**Comment by NicolasT** [comment]
@bert-e reset

**Comment by NicolasT** [comment]
@bert-e status

**Comment by NicolasT** [comment]
@bert-e status

**Comment by NicolasT** [comment]
@bert-e status

**Review by slaperche-scality — APPROVED** [review]

**Pull request merged**
