### PR TITLE
Upgrade Helm Version

### PR DESCRIPTION
**Pull request by ssalaues**
Implements the Helm version upgrade requested in #707 

Note: There are also references to the helm version in the `vendor/kubespray` folder and was unsure if it is preferred to updates those as well.

### CODE REVIEW

**Comment by NicolasT** [comment]
@bert-e status

**Comment by ssalaues** [comment]
I'm not sure what's wrong with Bert-e but it's possible that it doesn't quite know how to handle a PR from a fork too well.

**Comment by NicolasT** [comment]
Transplanting to our repo.

**Comment by ssalaues** [comment]
Closing in favor of #794

**Pull request closed without merging**
