### PR TITLE
NodeCreation: Add infra role

### LINKED ISSUE #1255: Node Management: Add "Infra" role
**Component**:UI

**Why this is needed**:
- Allow users to add "Infra" role to a node through the UI.

**What should be done**:
- Add a new "Infra" checkbox in the node creation form
- Based on the selected roles , create node with the appropriate taints and node roles by following the below table:

| Roles   | Node Roles        | Taints      |
|---------|-------------------|-------------|
| CP      | master,etcd       | master,etcd |
| WP      | node              |             |
| I       | infra             | infra       |
| CP,WP   | master,etcd,node       |             |
| CP,I    | master,etcd,infra | infra       |
| WP,I    | infra             |             |
| CP,WP,I | master,etcd,infra |             |

- Add the above table to the docs

**Implementation proposal** (strongly recommended):

**Test plan**:

### PR DESCRIPTION
**Pull request by carlito-scality**
**Component**:UI

**Context**: 
- Allow to add a new ```infra``` role when creating  node

**Summary**:

**Acceptance criteria**: 
- Create a new node with ```infra``` role
- Check if the role is correctly displayed in the node liste
- Deploy this node and check that the deployment is completed successfully.

Screenshot 2019-07-11 at 13 10 08

image

---

Closes: https://github.com/scality/metalk8s/issues/1255

### CODE REVIEW

**Review by gdemonet — COMMENTED** [review]
Code looks good to me, didn't test though (so I'll let someone else approve)

**Comment by carlito-scality** [comment]
@bert-e reset

**Review by MonPote — DISMISSED** [review]

**Comment by thomasdanan** [comment]
So from what I see in the screenshot and what I had during testing, expansion with infra checkbox is not scheduling the rights pods:
we are missing:
- prometheus
- alertmanager
- grafana
- metalk8s ui
- maybe kube state metric ?
- maybe prom operator ?

@xaf-scality @NicolasT can you help to define the right / expected list of PODs we should find on infra node ?

Actually, after discussing with @alexandre-allard-scality and @carlito-scality we may want to clarify acceptance criteria: if the problem to solve is to have HA for infra (i.e. we want monitoring service to be up whatever the node we lose, including bootstrap node) then a manual / auto test should be done to verify this and may be we are missing some stuffs to support lose of bootstrap node, migration of prom db (maybe handled by prom operator) etc ...

**Comment by carlito-scality** [comment]
@bert-e reset

**Comment by thomasdanan** [comment]
did several tests: kill pod, kill node ... pods are well scheduled on infra node ... only issues I see are the following:
- we are losing data when prom is scheduled on new infra node
- alert manager pods are not necessarily spread across the existing infra node
- we may want to increase replica when adding new infra node (for metal-ui or kube-state metrics, etc ...)

**Review by thomasdanan — APPROVED** [review]

**Comment by carlito-scality** [comment]
> did several tests: kill pod, kill node ... pods are well scheduled on infra node ... only issues I see are the following:
> 
> * we are losing data when prom is scheduled on new infra node
> * alert manager pods are not necessarily spread across the existing infra node
> * we may want to increase replica when adding new infra node (for metal-ui or kube-state metrics, etc ...)

Thanks @thomasdanan. I'll create an issue to address those problems. See https://github.com/scality/metalk8s/issues/1431

**Comment by carlito-scality** [comment]
@bert-e approve

**Pull request merged**
