### PR TITLE
ci: exit in error when all terraform retries fail

### PR DESCRIPTION
**Pull request by alexandre-allard**
**Component**: ci

**Context**: 

**Summary**:

**Acceptance criteria**:

### CODE REVIEW

**Review by gdemonet — DISMISSED** [review]
Thanks, would be nice to have this feature at the Eve step level... Feel free to open a feature request on their side, see if they have ideas, or maybe even submit a PR.

**Comment by alexandre-allard** [comment]
> Thanks, would be nice to have this feature at the Eve step level... Feel free to open a feature request on their side, see if they have ideas, or maybe even submit a PR.

Yes, it could be very cool ! I'll open an issue and if I have extra time at some point, will try to do it.

**Review by gdemonet — APPROVED** [review]

**Pull request merged**
