### PR TITLE
Update buildchain dependencies for Python 3.8

### PR DESCRIPTION
**Pull request by slaperche-scality**
**Component**:

buildchain

**Context**: 

Buildchain is not working with Python 3.8 because some dependencies are not compatible with it.

**Summary**:

Bump dependencies version.
Fix code where necessary.

**Acceptance criteria**: 

`./doit.sh` works with Python 3.8

---

Closes: #2064

### CODE REVIEW

**Review by jbertran — DISMISSED** [review]
With a freshly regenerated `doit` virtual environment and Python3.8:

```
$ python3
Python 3.8.0 (default, Oct 23 2019, 18:51:26) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
$ doit list
check_for         Check the existence of the external commands.
images            Pull/Build the container images.
iso               Build the MetalK8s image.
lint              Run the linting tools.
packaging         Build the packages and repositories.
populate_iso      Populate _build/root with required files.
salt_tree         Deploy the Salt tree in ISO_ROOT.
vagrant_restore   Restore development environment snapshot.
vagrant_up        Run `vagrant up` to (re-)provision a development environment.
```

LGTM, good luck with the babysitting...

**Review by gdemonet — DISMISSED** [review]
Still works with Python3.6 :+1:

**Review by jbertran — DISMISSED** [review]

**Review by jbertran — APPROVED** [review]

**Pull request merged**
