### PR TITLE
Remove (un)cordon functions from classic module

### PR DESCRIPTION
**Pull request by TeddyAndrieux**
**Component**:

'salt', 'kubernetes'

**Summary**:

Older cordon and uncordon functions still present in
`metalk8s_kubernetes.py` when we want to use the ones from
`metalk8s_cordon.py`. Both module use `metalk8s_kubernetes` as
virtualname so the function from `metalk8s_cordon.py` were ignored.

---

Fixes: #1738

### CODE REVIEW

**Comment by NicolasT** [comment]
Or, maybe better: have every module we have use `__name__` as its `__virtualname__`, and call *what we want* *exactly* instead of relying on this Salt module shadowing nonsense?

**Comment by TeddyAndrieux** [comment]
> Or, maybe better: have every module we have use `__name__` as its `__virtualname__`, and call _what we want_ _exactly_ instead of relying on this Salt module shadowing nonsense?

It's allow us to split functions in different python file and keep one entry point. Because if we separate `kubernetes` and `cordon` why we not also separate for example `node` and `pod`.
Maybe make sense to separate everything but I think have a separate "virtualname" only for cordon is not really good as both `metalk8s_kubernetes` and `metalk8s_cordon` are only about Apiserver interactions.

**Comment by NicolasT** [comment]
Fair enough :)

**Review by NicolasT — APPROVED** [review]

**Pull request merged**
