### PR TITLE
Bind kubelet to the control-plane IP address

### PR DESCRIPTION
**Pull request by cmonfort**
Fixes: #683

### CODE REVIEW

**Review by NicolasT — DISMISSED** [review]
Didn't test, but LGTM on sight. At some point, we should have a test-case which checks for all `LISTEN` ports on a server, and validates that list is a subset of a list of 'known OK' ports.

**Comment by cmonfort** [comment]
@bert-e aprove

**Comment by cmonfort** [comment]
@bert-e help

**Comment by cmonfort** [comment]
@bert-e approve

**Review by NicolasT — APPROVED** [review]

**Pull request merged**
