### PR TITLE
shell: Install and use Mitogen

### PR DESCRIPTION
**Pull request by NicolasT**
See: https://github.com/dw/mitogen
See: https://mitogen.readthedocs.io

### CODE REVIEW

**Comment by NicolasT** [comment]
@bert-e reset

**Comment by NicolasT** [comment]
@bert-e reset

**Comment by NicolasT** [comment]
@bert-e reset

**Comment by NicolasT** [comment]
@bert-e reset

**Review by ssalaues — APPROVED** [review]

**Pull request merged**
