### PR TITLE
Fix responsible on large screens

### PR DESCRIPTION
**Pull request by hug33k**
css: replace px by rem for Node/Volume/NodePageVolumes Table & NodePagePods/VolumeOverview Tab

**Component**:

NodeListTable, NodePagePodsTab, NodePageVolumesTable, VolumeListTable, VolumeOverviewTab

**Context**: 

On large screens, some components will have odd sizing, causing responsive issues.

**Summary**:

This PR replaces px values by rem values in order to add responsiveness to those components.

**Acceptance criteria**: 

This PR will fix some responsive issues and is related to [this PR](https://github.com/scality/core-ui/pull/383) on Core-UI, that will fix responsive for Core-UI components used by Metalk8s. PR on Core-UI needs to be merged first.

---

See: ARTESCA-2092 & ARTESCA-919

### CODE REVIEW

**Review by JBWatenbergScality — COMMENTED** [review]
Few enhancements to address:
When the left navbar is callapsed a scrollbar appears, can you make so no global scrollbar are displayed ?
In the volume detail tab Active alerts and usage are not aligned anymore
When the pod name to which the volume is bound is too long the layout is shifting the active alert and usage below, we would prefer for now to word-wrap the pod name to the next line.

**Comment by hug33k** [comment]
@JBWatenbergScality

1. Navbar issue when collapsed and hovered: This issue has been addressed in [this Core-UI PR](https://github.com/scality/core-ui/pull/388)
2. Misalignment issue for `Active alerts`& `Usage`: Fixed by commit 98cbb3b
3. Pod name too long causing layout issue on Volume Overview tab: Fixed by commit 98cbb3b

**Review by ChengYanJin — APPROVED** [review]

**Pull request merged**
