### PR TITLE
[security] Upgrade PyYAML from 5.1 to 5.3.1 (and other dependencies)

### PR DESCRIPTION
**Pull request by gdemonet**
Original change was proposed by Snyk. PR format was invalid however, and
edit of the requirements required running the `pip-compile` tox target.

The following vulnerabilities are fixed by pinning transitive dependencies:
- https://snyk.io/vuln/SNYK-PYTHON-PYYAML-559098

All integration branches were updated (by running `tox -e pip-compile` and bumping PyYAML version in `.in` requirement files).

---
Original PR: #2314

### CODE REVIEW

**Review by slaperche-scality — CHANGES_REQUESTED** [review]
That's not the only issue with Snyk's PR…

- we should also update the buildchain's requirements (it also uses PyYAML)
- if it's really a security issue it should probably be fixed in the oldest branches (for tests I don't know which one it is, but for buildchain we use PyYAML since 2.5)

Also it's still not clear to me that we're affected by the mentioned vulnerabilities (but anyway, it won't hurt to update).

**Comment by gdemonet** [comment]
> That's not the only issue with Snyk's PR…
> 
> * we should also update the buildchain's requirements (it also uses PyYAML)

Indeed, will go through the other places where PyYAML is used.

> * if it's really a security issue it should probably be fixed in the oldest branches (for tests I don't know which one it is, but for buildchain we use PyYAML since 2.5)

Ah right, the Snyk PR was targeting 2.0 already (so I changed the target of this branch). Maybe that's why buildchain was not changed by Snyk.

> Also it's still not clear to me that we're affected by the mentioned vulnerabilities (but anyway, it won't hurt to update).

Indeed, we probably aren't (it's affecting the `full_load` method, which I don't recall us using - but we depend on libraries which use `PyYAML`, so better upgrade than be sorry later).

**Review by TeddyAndrieux — DISMISSED** [review]

**Review by slaperche-scality — DISMISSED** [review]
What about ` buildchain/requirements-Darwin.txt`?

**Comment by gdemonet** [comment]
Ah, right. I'll borrow a Mac.

**Review by TeddyAndrieux — APPROVED** [review]

**Pull request merged**
