### PR TITLE
Improvement #496: use helm_cli to install prometheus

### PR DESCRIPTION
**Pull request by alexandre-allard**
This PR needs #498 in order to work (timeout option in helm_cli module).

### CODE REVIEW

**Review by NicolasT — CHANGES_REQUESTED** [review]
Needs a ChangeLog entry.

**Comment by alexandre-allard** [comment]
@NicolasT In which section should I put this ? It's not really a feature nor a bug, more a refactoring, but there is no such section in the document and its example. Should I create a new section type "refactoring" or put it in "features added" ? (I will also do it in my other PR for the timeout option).

**Review by Zempashi — DISMISSED** [review]

**Comment by alexandre-allard** [comment]
Got my answer from @Zempashi, changes pushed.

**Review by ballot-scality — APPROVED** [review]
LGTM.

**Review by NicolasT — APPROVED** [review]
In future, take care of capitalization (`Prometheus` is a proper name). We'll do an overhaul of all ChangeLog entries before release to fix this.

**Comment by alexandre-allard** [comment]
@bert-e approve

**Pull request merged**
