### PR TITLE
Fix python2 kubernetes 10.0.1 changes

### PR DESCRIPTION
**Pull request by TeddyAndrieux**
**Component**:

'salt', 'kubernetes'

**Context**: 

`python2-kubernetes` version 10.0.1 just get pushed in epel repository so we need to add compatibilty with this.

**Summary**:

For example model `V1beta1Ingress` get removed from this version

---

### CODE REVIEW

**Review by slaperche-scality — APPROVED** [review]

**Comment by flavien-scality** [comment]
/bypass_build_status

As asked by @TeddyAndrieux :
> I will need a bypass_build_status for my metalk8s PR https://github.com/scality/metalk8s/pull/2073
Short story: A new version of python2-kubernetes get released in epel and break install
This PR fix the problem but we have "ugly test" that build current "dev" branchs to do some upgrade/downgrade test but dev branch no longer build as need this PR to land :slightly_smiling_face: #chickenAndEgg

**Pull request merged**
