### PR TITLE
improvement: upgrades 1.11 kubernetes for CVE fixes

### PR DESCRIPTION
**Pull request by ssalaues**
Fixes: #1053

### CODE REVIEW

**Comment by ssalaues** [comment]
@bert-e after_pull_request=1040

**Comment by NicolasT** [comment]
Will you update this one to 1.11.10? Thanks!

**Comment by ssalaues** [comment]
Oh wow it's good timing that they just released a new version. I'll update the PR.

**Review by NicolasT — APPROVED** [review]
LGTM

**Pull request merged**
