### PR TITLE
Use PTY to get build step output in CI

### PR DESCRIPTION
**Pull request by gdemonet**
Fixes GH-867

### CODE REVIEW

**Review by slaperche-scality — COMMENTED** [review]
Could add some context in the commit message (why we do that, buffering stuff, …).

Link to issue is nice but useless when working offline/GitHub is down.

**Comment by gdemonet** [comment]
Commit message updated with more details @slaperche-scality

**Comment by gdemonet** [comment]
@bert-e reset

**Comment by gdemonet** [comment]
@bert-e approve

**Review by slaperche-scality — APPROVED** [review]

**Pull request merged**
