### PR TITLE
Remove VERSION_SUFFIX  from Eve "product_version"

### LINKED ISSUE #1166: eve/get_product_version.sh should only output numbers separated by a dot
**Component**:

'build'

**What happened**:

artifacts are not processed by expiration and promotion, due to a version considered as invalid in the artifacts_name property

**What was expected**:

correct processing of artifacts expiration (ie good format of get_product_version.sh output)

**Steps to reproduce**

see builds listing, entries with a version suffix have not been expired.

**Resolution proposal** (optional):

fix all dev branches having the issue by removing the VERSION_SUFFIX of the output. If you want to use the current format of the suffixed version, please do not use get_product_version for that, as it is designed and used by the CI with its own requirements.

### PR DESCRIPTION
**Pull request by gdemonet**
**Component**: build

---

Closes: #1166

### CODE REVIEW

**Review by slaperche-scality — CHANGES_REQUESTED** [review]
Should explain WHY this change in the commit message.

**Comment by gdemonet** [comment]
> Should explain WHY this change in the commit message.

Done

**Comment by gdemonet** [comment]
@bert-e reset

**Review by slaperche-scality — APPROVED** [review]

**Comment by gdemonet** [comment]
@bert-e approve

**Pull request merged**
