### PR TITLE
No longer deploy Solution UIs

### LINKED ISSUE #2581: Solution framework should not deploy Solution UIs
**Component**: salt, solutions

**Why this is needed**:

**What should be done**:
Remove the deployment of Solution UI and let the Operator of the Solution handle it.

**Implementation proposal** (strongly recommended):
Just remove the UI part of the Salt `salt/metalk8s/orchestrate/solutions/prepare-environment.sls` formula and the related files under `salt/metalk8s/orchestrate/solutions/files/ui`.
There is also probably some changes to do on the MetalK8s UI Environment page.

**Test plan**:
There already are pytest and cypress tests developed, they should be updated accordingly.

### PR DESCRIPTION
**Pull request by alexandre-allard**
**Component**: salt, solutions, examples

**Context**: See #2581 

**Summary**:
Solution UIs are no longer deployed by the Solution framework

**Acceptance criteria**:
Solution tests should be green.

---

Closes: #2581

### CODE REVIEW

**Review by Ebaneck — DISMISSED** [review]
:shipit:

**Comment by Ebaneck** [comment]
Agreed to merge this after the release

**Comment by gdemonet** [comment]
Maybe target `2.6`, given it's quite the breaking change @alexandre-allard-scality 

Also, can we make sure people involved agree with the "new" design? Naming a few: @MonPote @nicolas2bert @slaperche-scality @RachedBenMustapha

**Comment by alexandre-allard** [comment]
@gdemonet since we already broke the Solutions with the new manifest... I thought we could do everything in the same version. :)

**Comment by gdemonet** [comment]
Maybe... Better to ask than to hope :stuck_out_tongue_winking_eye:

**Comment by alexandre-allard** [comment]
This PR is now targeting `development/2.6`

**Review by gdemonet — CHANGES_REQUESTED** [review]
Let's add an entry in the CHANGELOG and then merge it :)

**Comment by alexandre-allard** [comment]
@gdemonet done in dd2c3b2df69c5733ce36e4737bdde5812a3c3382

**Review by gdemonet — APPROVED** [review]

**Pull request merged**
