### PR TITLE
ui: remove from project

### PR DESCRIPTION
**Pull request by NicolasT**
Since the MetalK8s UI is not maintained before MetalK8s 2.4 (though it
was bootstrapped with MetalK8s 2.0), we decided to remove it from the
`development/2.0`, `development/2.1`, `development/2.2` and
`development/2.3` branches.

This commit removes the UI code, its packaging, its deployment and
documentation referring to it.

### CODE REVIEW

**Comment by NicolasT** [comment]
@bert-e wait

**Comment by NicolasT** [comment]
Will need to ensure all of this is undone in the `development/2.4` integration.

**Comment by NicolasT** [comment]
@bert-e help

**Comment by NicolasT** [comment]
@bert-e create_pull_requests

**Comment by NicolasT** [comment]
@bert-e reset

**Comment by NicolasT** [comment]
@bert-e status

**Comment by NicolasT** [comment]
For reviewers: https://github.com/scality/metalk8s/pull/1577 shows the integration with `development/2.4` will introduce 0 changes.

The integration branch was created according to @bert-e's conflict resolution commands it posted above, however using `-s ours` at the `git merge` phase to not accept any 'upstream' (i.e., `feature/remove-ui-2.0123`) changes, and keep the *content* of `development/2.4` intact.

**Review by MonPote — APPROVED** [review]
LGTM

**Pull request merged**
