### PR TITLE
Remove nodes-darwin dashboard from kube-prometheus-stack

### PR DESCRIPTION
**Pull request by eg-ayoub**

### CODE REVIEW

**Review by TeddyAndrieux — DISMISSED** [review]
LGTM

**Comment by eg-ayoub** [comment]
ping

**Comment by eg-ayoub** [comment]
ping

**Comment by eg-ayoub** [comment]
ping

**Review by TeddyAndrieux — APPROVED** [review]

**Comment by eg-ayoub** [comment]
ping

**Pull request merged**
