### PR TITLE
Bump versions for development/2.4

### PR DESCRIPTION
**Pull request by gdemonet**
**Component**: kubernetes

**Context**: Creation of the `development/2.4` branch

**Acceptance criteria**: CI green builds

---

Closes: #1394

### CODE REVIEW

**Review by NicolasT — DISMISSED** [review]
LGTM

**Review by NicolasT — APPROVED** [review]
LGTM is CI agrees.

**Comment by gdemonet** [comment]
@bert-e approve

**Comment by NicolasT** [comment]
@bert-e status

**Pull request merged**
