### PR TITLE
[Integration branch]To merge all Node PRs

### LINKED ISSUE #2775: [UI New Node Page] Add alerts table in Node Page
**Component**: ui, nodes

**Why this is needed**:
- We want to see all the active alerts related to this node.
- With the filter component to filter the alert base on severity.
 
**What should be done**:
- We should retrieve the alerts from `Alertmanager` and list all the alerts in the table

- When we add the severity filter the URL should update too.
`/newNodes/<node-name>/alerts?severity=<critical/warning>`
- Remove the info selector because we only have critical and warning for the moment for Node
- if there is no severity selected then no alert display. 
- When we come to the alert tab from the tab selection, by default display all the alerts(both critical and warning)
  the URL should be: `/newNodes/<node-name>/alerts?severity=critical,warning` or
  or `/newNodes/<node-name>/alerts?severity=critical&severity=warning`

**Implementation proposal** (strongly recommended):

**Update proposal**
image

Hardcode the alerts related to nodes in frontend.

Store all the selected severity in an array

const selectedSeverity = [ ];

const [isCriticalSelected, setIsCriticalSelected] = useState();
const [isWarningSelected, setIsWarningSelected] = useState();

**Test plan**:
TBD

### LINKED ISSUE #2777: [UI New Node Page] Add volume tab in Node page
**Component**: ui, nodes

**Why this is needed**:

**What should be done**:
- implement the volume as designed.
- When I select one volume, I should go to the volume page with the filter by the current node

**Implementation proposal** (strongly recommended):
image

After discussing with Thomas, we should have the same table as the table in Volume Page, but without the node field.
Another difference is the Onclick() function, we want to go the volume page when we click on the one volume.

**Test plan**:
TBD

### LINKED ISSUE #2791: [UI New Node Page] Node deployment
**Component**: ui, nodes
**Why this is needed**:

**What should be done**:
05-03-node-v4-deploying@2x

**Implementation proposal** (strongly recommended):
- Display the `Node Deployment` component in the `Health tab` during the deployment and failed deployment (for the success deployment, in the future we will replace it by the health status bar to display the health of last 7days)

   **To be confirmed**: For the success deployment, do we still keep the Node Deployment component after the deployment is done?

- When click on the `Go to logs` we should be redirected to Grafana to get `salt master` log, the default time window should be the `last 3 hours`.
- Display the error message (notification) for the failed deployment node
- For the non deployed node and failed deployed node, we still should display all the tabs to provide the same UX
- Compare the design, replace the Delete button by `Deploy` button
- Display the Create time instead of Last Updated
- Have 2 separated IPs: Control Plane IP and Workload Plane IP

Update:
- Remove the Labels and Annotations
- We only display the Node Deployment component during the deployment or there is an error during the deployment.

**Test plan**:
TBD

### LINKED ISSUE #2802: [UI New Node Page] Change the Node Page from temporary URL to '/nodes'
**Component**: UI

**Why this is needed**:
We are using the temporary URL for the New Node Page, in order to merge the WIP New Node Page and have the old Node Page accessible at the same time.

**What should be done**:
Once we are done with the New Node Page, we should change the current temporary URL to the `/nodes` and remove the unused props roleTaintMatched and roleTaintMatched and the corresponding role props (bootstrap, infra, control_plane, and workload_plane)

**Implementation proposal** (strongly recommended):
TBD

**Test plan**:
TBD

### LINKED ISSUE #2877: [UI] Always select first entry in table views (Nodes, Volumes) by default
**Component**: ui

**Why this is needed**: It feels disturbing to see the right side be empty when landing on those pages

**What should be done**: When landing on a table view page (`/nodes`, `/volumes`), always select the first item from the list by default (account for sorting rules, either from URL params or using defaults).

**Implementation proposal** (strongly recommended):

**Test plan**:

- Add some integration tests to ensure the expected item is selected based on the various sorting rules implemented

### PR DESCRIPTION
**Pull request by ChengYanJin**
**Component**: ui, nodes

**Context**: 
The integration branch with all the Node Page PRs to be merged.

**Summary**: 
The new commits that do not cover in the open PRs
- Rename from `/newNodes` to `/nodes`
- Auto select the first node in the list when hit URL `/nodes`
- Add `Advanced Metrics` button in Metrics. (Need to figure out how to redirect to the dashboard specific for this node)
- Retrieve unode-name from Prometheus in order to be redirect to the right Node Detailed dashboard in Grafana

**Acceptance criteria**: 
Overview Tab:
image
image
Metrics Tab:
image
Volume Tab:
image
Pod Tab:
image
Detail Tab:
image

---

Closes: #2877
Closes: #2775
Closes: #2791
Closes: #2777 
Closes: #2802

### CODE REVIEW

**Review by thomasdanan — COMMENTED** [review]
Excellent !!!

I noticed few things: 

- the advanced metrics link (in metrics tab) was not bringing me to the right node instance
- If I click on Create Node and Cancel, the node selection from where I was coming from is lost.
- still see the little bug about capacity usage bar
- I realize that it is not obvious that one node is having one Volume which is in Critical state. We may want this to appear in the tab header (more or less like we do for alerts: displaying number of Volumes and maybe number of volumes in critical health) => probably another improvement ticket
- If I search a node with some free text in the search bar, then if I select a node and start navigating through the tabs, the search filter is not applied anymore (and is removed from url)
- ideally, the up/down arrow key should let the user switching from one node to another

**Comment by ChengYanJin** [comment]
Hi @thomas,
Thanks for the early feedback!

I fixed the bugs/issues you raised in the comments. 
But not these two bullet points. I will create tickets to track them. 
- I realize that it is not obvious that one node is having one Volume which is in Critical state. We may want this to appear in the tab header (more or less like we do for alerts: displaying number of Volumes and maybe number of volumes in critical health) => probably another improvement ticket


- ideally, the up/down arrow key should let the user switching from one node to another

**Review by thomasdanan — DISMISSED** [review]

**Review by thomasdanan — APPROVED** [review]

**Pull request merged**
