### PR TITLE
Disable GitHub Actions

### PR DESCRIPTION
**Pull request by gdemonet**
GitHub Actions were disabled, hence all configured workflows are failing and prevent other PRs from merging.

This removes the `.github/workflows` directory, until Actions are re-enabled.

### CODE REVIEW

**Comment by slaperche-scality** [comment]
> GitHub Actions were disabled, hence all configured workflows are failing and prevent other PRs from merging.
>
> This removes the .github/workflows directory, until Actions are re-enabled.

Would be nice to have this in the commit message :wink:

**Review by NicolasT — APPROVED** [review]
Too bad :cry:

**Comment by gdemonet** [comment]
> Do we know why they disabled it?

It was a beta feature, now it's not part of our plan :dollar:

**Comment by slaperche-scality** [comment]
> > Do we know why they disabled it?
> 
> It was a beta feature, now it's not part of our plan dollar

Ha, the famous "it's free if you only have public repo OR if you pay enough money", same reason why we can't have Draft PR on our private repo (like HD ones)…

**Comment by gdemonet** [comment]
> Ha, the famous "it's free if you only have public repo OR if you pay enough money", same reason why we can't have Draft PR on our private repo (like HD ones)…

Then shouldn't it work for this repo, which is public? :thinking:

**Comment by slaperche-scality** [comment]
> > Ha, the famous "it's free if you only have public repo OR if you pay enough money", same reason why we can't have Draft PR on our private repo (like HD ones)…
> 
> Then shouldn't it work for this repo, which is public? thinking

Not the exact same policy then.
For draft PR you're allowed to have tainted repo, but for action you need to have a pure heart :laughing:

**Pull request merged**
