### PR TITLE
Rename custom kubernetes module into metalk8s_kubernetes

### PR DESCRIPTION
**Pull request by ramanduh**
Fix: #991

### CODE REVIEW

**Review by NicolasT — CHANGES_REQUESTED** [review]
Please rename the modules to `metalk8s_kubernetes` as well instead of only modifying the `__virtualname__`. Other than that, LGTM if CI agrees.

**Comment by ramanduh** [comment]
@bert-e reset

**Comment by ramanduh** [comment]
@bert-e approve

**Comment by ramanduh** [comment]
@bert-e reset

**Review by NicolasT — APPROVED** [review]
OK if CI agrees.

**Comment by NicolasT** [comment]
@bert-e status

**Pull request merged**
