### PR TITLE
charts,salt,build: Bump Loki chart to 2.9.1

### PR DESCRIPTION
**Pull request by TeddyAndrieux**
Bump the Loki chart to 2.9.1 and also bump the Loki image to 2.4.2

### CODE REVIEW

**Comment by alexandre-allard** [comment]
Since it now seems supported, shouldn't we use the `networking.k8s.io/v1` `apiVersion` for `Ingress` object instead of the former one.

**Comment by TeddyAndrieux** [comment]
> Since it now seems supported, shouldn't we use the `networking.k8s.io/v1` `apiVersion` for `Ingress` object instead of the former one.

Euh yes sure, and I think we already do use it everywhere no ?
And for Loki we do not deploy the Ingress so ... not really linked to this PR

```console
$ git grep -B 1 "kind: Ingress" salt/
salt/metalk8s/addons/dex/deployed/chart.sls-apiVersion: networking.k8s.io/v1
salt/metalk8s/addons/dex/deployed/chart.sls:kind: Ingress
--
salt/metalk8s/addons/nginx-ingress-control-plane/deployed/chart-daemonset.sls-apiVersion: networking.k8s.io/v1
salt/metalk8s/addons/nginx-ingress-control-plane/deployed/chart-daemonset.sls:kind: IngressClass
--
salt/metalk8s/addons/nginx-ingress-control-plane/deployed/chart-deployment.sls-apiVersion: networking.k8s.io/v1
salt/metalk8s/addons/nginx-ingress-control-plane/deployed/chart-deployment.sls:kind: IngressClass
--
salt/metalk8s/addons/nginx-ingress/deployed/chart.sls-apiVersion: networking.k8s.io/v1
salt/metalk8s/addons/nginx-ingress/deployed/chart.sls:kind: IngressClass
--
salt/metalk8s/addons/prometheus-operator/deployed/chart.sls-apiVersion: networking.k8s.io/v1
salt/metalk8s/addons/prometheus-operator/deployed/chart.sls:kind: Ingress
--
salt/metalk8s/addons/ui/deployed/ingress.sls-apiVersion: networking.k8s.io/v1
salt/metalk8s/addons/ui/deployed/ingress.sls:kind: Ingress
--
salt/metalk8s/addons/ui/deployed/ingress.sls-apiVersion: networking.k8s.io/v1
salt/metalk8s/addons/ui/deployed/ingress.sls:kind: Ingress
--
salt/metalk8s/addons/ui/deployed/ingress.sls-apiVersion: networking.k8s.io/v1
salt/metalk8s/addons/ui/deployed/ingress.sls:kind: Ingress
--
salt/metalk8s/addons/ui/deployed/ingress.sls-apiVersion: networking.k8s.io/v1
salt/metalk8s/addons/ui/deployed/ingress.sls:kind: Ingress
```

**Comment by alexandre-allard** [comment]
Oh ok, you're right, my bad.

**Review by alexandre-allard — APPROVED** [review]

**Pull request merged**
