### PR TITLE
[ui] delete the job when there is error occur

### PR DESCRIPTION
**Pull request by ChengYanJin**
**Component**: node

**Context**: 
There is no error handler when SALT indicates the error inside the JSON

**Summary**:
Since it's not easy to reproduce the bug, I'll just first add an error handler.

**Acceptance criteria**: 

---

Closes: #ISSUE_NUMBER

### CODE REVIEW

**Comment by gdemonet** [comment]
Aren't we missing error handling if SaltAPI doesn't answer / gives a bad status **at the HTTP level**?

**Comment by ChengYanJin** [comment]
> Aren't we missing error handling if SaltAPI doesn't answer / gives a bad status **at the HTTP level**?

You are right! There are two errors we need to handle actually
- HTTP error (4xx, 5xx)
- Salt error (code 2xx, but error in the response)

**Review by MonPote — APPROVED** [review]
LGTM.
We really need to design a better way to handle salt error. But it's not the purpose of this PR.

**Pull request merged**
