### PR TITLE
salt: change salt-master config generation

### PR DESCRIPTION
**Pull request by slaperche-scality**
In order to support several `saltenv` at the same time (e.g. during an
upgrade), we now generate the configuration file with `file.serialize`
and `merge_if_exists` set to `True`.
With that change, when you re-run the state with a new `saltenv`,
instead of overwriting the existing one it will add a new entry in the
dict.

## How to test

- Spawn a bootstrap node: `./doit.sh vagrantup`
- Run `salt-call state.apply metalk8s.salt.master.configured saltenv=metalk8s-2.0`: No changes
- Edit `/etc/salt/master.d/99-metalk8s.conf`, replacing `2.0` by `2.1` (to simulate a new `saltenv`).
- Re-run `salt-call state.apply metalk8s.salt.master.configured saltenv=metalk8s-2.0`: the file is modified, we now have two entries:
  - the manual one (2.1) is still here, not overwritten
  - the current one (2.0) is added

Closes: #800
Signed-off-by: Sylvain Laperche <sylvain.laperche@scality.com>

### CODE REVIEW

**Comment by NicolasT** [comment]
IMO we should have two files in `master.d`:

- One which contains 'static' configuration that may get overwritten, but not merged, because then it's hard (to say at least) to somewhat deterministically know what's in the file post deployment
- One which contains `top_roots` and `file_roots`, and which *is* updated by 'merging' values upon updates

**Comment by slaperche-scality** [comment]
> IMO we should have two files in `master.d`:
> 
>     * One which contains 'static' configuration that may get overwritten, but not merged, because then it's hard (to say at least) to somewhat deterministically know what's in the file post deployment
> 
>     * One which contains `top_roots` and `file_roots`, and which _is_ updated by 'merging' values upon updates

Done

**Comment by slaperche-scality** [comment]
@bert-e reset

**Review by gdemonet — APPROVED** [review]
LGTM

**Review by TeddyAndrieux — APPROVED** [review]

**Comment by slaperche-scality** [comment]
@bert-e approve

**Pull request merged**
