### PR TITLE
UI: Sexiness improvement

### PR DESCRIPTION
**Pull request by carlito-scality**
**Component**:UI

**Context**: 
- fix sidePanel icon alignment
- "no rows" translations when table is empty
- columns node list resizing

**Summary**:

**Acceptance criteria**: 
Screenshot 2019-07-16 at 11 29 23

- icons in sidePanel should be aligned
- when the table is empty, it should display "no data available" and when we switch the language, it should be translated.

---

Closes: #ISSUE_NUMBER

### CODE REVIEW

**Comment by carlito-scality** [comment]
@bert-e reset

**Comment by carlito-scality** [comment]
@bert-e reset

**Review by ChengYanJin — APPROVED** [review]
It works!

**Review by thomasdanan — APPROVED** [review]

**Comment by carlito-scality** [comment]
@carlito-scality approve

**Comment by carlito-scality** [comment]
@bert-e approve

**Pull request merged**
