### PR TITLE
Backport PR 1631 to 2.0

### PR DESCRIPTION
**Pull request by slaperche-scality**
**Component**:

salt

**Context**: 

Since HTTPS is a security feature, we want it in 2.0 (and also to ease the migration).

**Summary**:

Thanks to atomic commits, it's only a matter of cherry-picking:
- 5e29246e, 09a7fad1, fbbab308 were left out because UI doesn't exist (was removed in fact) before 2.4
- 428ea9b2 was left out because the storage operator was introduced in 2.4

All the other commit were cherry-picked as-is (just a small conflict resolution for 96416a50).

**Acceptance criteria**: 

See https://github.com/scality/metalk8s/pull/1631

---

See: #1115

### CODE REVIEW

**Comment by NicolasT** [comment]
LGTM on first sight.

**Comment by slaperche-scality** [comment]
No diff in https://github.com/scality/metalk8s/pull/1645, as expected/as it should be.

**Review by charlesprost — APPROVED** [review]

**Comment by slaperche-scality** [comment]
Now we have a diff for #1645 (and it's expected).

The test with the ping was buggy in 2.4 to begin with, but went unnoticed because my new test "auth with token" shadowed/replaced the "auth with Basic auth"…

I'll do a fix in 2.4 once this PR is merged (could have done it here, but I'm not fond of fixing bug during merge commit, bad for tracking)

**Pull request merged**
