### PR TITLE
Fix build infrastructure for MacOS X

### PR DESCRIPTION
**Pull request by thomasdanan**
just to have Makefile works on macos

### CODE REVIEW

**Comment by slaperche-scality** [comment]
No problem with the long options of `mkisofs`? Only `cp` was an issue?

**Review by NicolasT — DISMISSED** [review]

**Comment by NicolasT** [comment]
@thomasdanan You'll need to self-approve as well.

**Comment by thomasdanan** [comment]
@slaperche-scality @NicolasT indeed I did not test ISO generation (as it is not called in default target) ... so I have to install crdtools do a kind of manual sym link after brew install and now I get some errors I would need to fix ...
Also that makes me think that we should list pre reqs somewhere

**Comment by NicolasT** [comment]
Default target builds the ISO (as it should, because it's the final and only deliverable) when #572 goes in.

**Comment by thomasdanan** [comment]
so for now the issue is -checksum_algorithm_iso is not recognise option of mkisofs on my env ...

**Comment by slaperche-scality** [comment]
> so for now the issue is -checksum_algorithm_iso is not recognise option of mkisofs on my env ...

Yup, can't find this option on my system as well (see https://github.com/scality/metalk8s/pull/566#discussion_r255935387)
I think it's either something Debian-specific (but seems not) or `genisoimage` embeds a patched version of `mkisofs`.

This option seems related to "Jigdo production" (from https://lists.debian.org/debian-boot/2012/03/msg00445.html).

**Comment by NicolasT** [comment]
Then remove said option.

**Comment by thomasdanan** [comment]
@bert-e approve

**Review by NicolasT — APPROVED** [review]

**Pull request merged**
