### PR TITLE
build: Bump K8s version to 1.18.10

### PR DESCRIPTION
**Pull request by TeddyAndrieux**
**Component**:

'build'

**Context**: 

Bump kubernetes version embedded in MetalK8s

---

### CODE REVIEW

**Review by gdemonet — DISMISSED** [review]

**Comment by Ebaneck** [comment]
Are we missing a `Changelog` entry?

**Comment by TeddyAndrieux** [comment]
> Are we missing a `Changelog` entry?

Not in this PR, I will do it later

**Comment by gdemonet** [comment]
@TeddyAndrieux the extra commit (10557c2b6a2c5e83f81a7eb3357a202833f8fc6b) Bert-E is talking about shouldn't be in this branch, right? If so, maybe close the PR and delete the branch?

**Comment by TeddyAndrieux** [comment]
Yes I just saw this one, it's a fail on my side, let's close this PR

**Pull request closed without merging**
