### PR TITLE
docs: Explain how to create a ClusterRoleBinding on groups

### LINKED ISSUE #3043: Update Default Dex configuration to allow group fetching
**Component**:

'dex'

**Why this is needed**:

Currently, we cannot properly define a clusterrole binding between a group and a cluster role when dex is integrated with an external OIDC IDP. Actually, the default configuration of dex we deploy doesn't allow it. Also, the documentation we provide to guide the user when creating clusterrolebinding is focusing on user to cluster-role binding but one other important use case would be between group and cluster-role. We should add an example for such configuration.

**What should be done**:

- update default dex configuration to allow group fetch from external OIDC
- update the documentation to explain how to create a clusterrolebinding between group and cluster-role

**Implementation proposal** (strongly recommended):

**Test plan**:

### PR DESCRIPTION
**Pull request by alexandre-allard**
**Component**: docs

**Context**:
We need to be able to bind Keycloak group to role in K8s.

**Summary**:
Explain how to create a ClusterRoleBinding on a group.

**Acceptance criteria**: n/a

---

Closes: #3043

### CODE REVIEW

**Review by gdemonet — APPROVED** [review]
LGTM. Just wondering if we thought about adding a prefix to OIDC users (using `--oidc-groups-prefix` and `--oidc-username-prefix`), which is recommended to avoid conflicts with other authentication methods.

**Comment by alexandre-allard** [comment]
@gdemonet No, but that's a good idea, I'll create an issue to track this.

**Comment by NicolasT** [comment]
We *must* use such prefix, otherwise there are some glaring security issues. That's a blocker (I though we were already having those...)

**Pull request merged**
