### PR TITLE
Set up multi-network Vagrant VMs, and fix kubelet node IP reporting

### PR DESCRIPTION
**Pull request by NicolasT**
- Set up two separate private networks in Vagrant, one for the control-plane, one for the workload-plane, and attach VMs to them

  Note: the IPs used for these networks are not the ones used before. I moved to a `172.16.0.0/16` network to reduce the chances of collision with existing networks (`192.168.0.0/16` is slightly more 'popular' in home/SOHO networks).

- Configure `kubelet` to register itself with the node IP in the control-plane it also binds to.
- Add a test to check we can `kubectl exec` something in a Pod, which requires the above to be set up correctly (and is how the issue was discovered in the first place).

- Implement and enforce site-local networking configuration: previously, we had some control-plane and workload-plane networks configured 'by default', which was arbitrary. This PR introduces a `bootstrap.yaml` configuration file and a simple 'external Pillar' to read and validate the file, and expose its content as Pillar values.

Fixes: #768
Fixes: #769
Fixes: #776

### CODE REVIEW

**Comment by charlesprost** [comment]
@NicolasT something is weird. I've just tried your PR, started bootstrap and node2, and they seem to have the IP addresses.

```
[vagrant@bootstrap ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:84:81:d5 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic eth0
       valid_lft 85531sec preferred_lft 85531sec
    inet6 fe80::5054:ff:fe84:81d5/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:7a:31:03 brd ff:ff:ff:ff:ff:ff
    inet 172.21.254.3/28 brd 172.21.254.15 scope global noprefixroute dynamic eth1
       valid_lft 912sec preferred_lft 912sec
    inet6 fe80::a00:27ff:fe7a:3103/64 scope link 
       valid_lft forever preferred_lft forever
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:27:6c:72 brd ff:ff:ff:ff:ff:ff
    inet 172.21.254.35/27 brd 172.21.254.63 scope global noprefixroute dynamic eth2
       valid_lft 908sec preferred_lft 908sec
    inet6 fe80::a00:27ff:fe27:6c72/64 scope link 
       valid_lft forever preferred_lft forever
```

and

```
[vagrant@node2 ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:84:81:d5 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic eth0
       valid_lft 86356sec preferred_lft 86356sec
    inet6 fe80::5054:ff:fe84:81d5/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:53:6a:64 brd ff:ff:ff:ff:ff:ff
    inet 172.21.254.3/28 brd 172.21.254.15 scope global noprefixroute dynamic eth1
       valid_lft 1156sec preferred_lft 1156sec
    inet6 fe80::a00:27ff:fe53:6a64/64 scope link 
       valid_lft forever preferred_lft forever
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:76:7d:91 brd ff:ff:ff:ff:ff:ff
    inet 172.21.254.35/27 brd 172.21.254.63 scope global noprefixroute dynamic eth2
       valid_lft 1156sec preferred_lft 1156sec
    inet6 fe80::a00:27ff:fe76:7d91/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by NicolasT** [comment]
Heh, good point. However, they don't really get the 'same' IP: open `VirtualBox`, and check the networks (`File -> Host Network Manager`). You'll see four (or more) networks, two for each VM, with the same configuration. Similarly `ip a` on your host will show `vboxnet*` interfaces with the corresponding networks, duplicated.

This is of course not the intent (and won't work). Hmh... Will look into it.

**Comment by sayf-eddine-scality** [comment]
> Heh, good point. However, they don't really get the 'same' IP: open `VirtualBox`, and check the networks (`File -> Host Network Manager`). You'll see four (or more) networks, two for each VM, with the same configuration. Similarly `ip a` on your host will show `vboxnet*` interfaces with the corresponding networks, duplicated.
> 
> This is of course not the intent (and won't work). Hmh... Will look into it.

I guess this is coming from the merged PR https://github.com/hashicorp/vagrant/issues/5293#issuecomment-73021304

**Comment by NicolasT** [comment]
Fixed it. Misinterpretation of the Vagrant code on my side initially, then also a bug in Vagrant (see code comments).

**Comment by charlesprost** [comment]
@NicolasT now it's working great ;-) we'll have to find a way to discover which IPs are used and by which hosts, so we could add them somehow in the cluster later, but that's another story

**Comment by NicolasT** [comment]
> we'll have to find a way to discover which IPs are used and by which hosts, so we could add them somehow in the cluster later, but that's another story

Adding nodes is always a UI/API-driven process, so we can assume user to provide an IP address, which can easily be looked up using something like `vagrant ssh nodeN ip a` or similar.

**Review by charlesprost — APPROVED** [review]

**Comment by NicolasT** [comment]
@bert-e approve

**Pull request merged**
