### PR TITLE
Allow to customize services with custom values.yml files

### PR DESCRIPTION
**Pull request by virtuman**
Suggestion for allowing to customize deployed services related to #230 and #246 

Supported customizable roles (can add all of them, but i added only ones that we already customize as an example, to get this going):
- kube_nginx_ingress
- cluster_logging/elasticsearch
- cluster_logging/elasticsearch-curator
- cluster_logging/kibana

place override `values.yml` file in `{{ inventory_dir}}/customization/*role-path*/values.yml` like this:
`{{ inventory_dir }}/customization/kube_nginx_ingress/values.yml`
`{{ inventory_dir }}/customization/cluster_logging/elasticsearch/values.yml`
`{{ inventory_dir }}/customization/cluster_logging/elasticsearch-curator/values.yml`
`{{ inventory_dir }}/customization/cluster_logging/kibana/values.yml`

Intentionally using `with_fileglob` instead of silent file existence check, so that playbook generates additional output, indicating that this playbook supports overriding values.yml. For example, it will say ` [WARNING]: Unable to find '/Users/.../metal-k8s/inventory/devcluster/customizations/cluster_logging/kibana' in expected paths (use -vvvvv to see paths)z

### CODE REVIEW

**Comment by NicolasT** [comment]
@virtuman I'm traveling right now so please allow me some time to get back to this.

In order to get this merged eventually, you'll need to put a signature in your commits and assert your work is in line with the DCO. This is currently not enforced by CI but we're working on that. See https://github.com/scality/metalk8s/pull/254/commits/90a90b650fa321097c24c3fdd8b5bc62c1a560b0

Please amend the commit message accordingly, and state your contribution is in line with the DCO in a comment of this PR (for now) if possible :)

**Comment by virtuman** [comment]
Sure thing. Just amended commit message. Mind you - I never used ansible before, and I totally understand if the suggested approach that I used here is completely invalid. This is something that currently works for me for deploying my clusters.

**Comment by NicolasT** [comment]
@virtuman Now #238 landed, do you think it'd make sense to use that approach instead of using files in an inventory directly?

Using the new `helm_cli` module, we can update all roles to use this module, and get 'custom' Chart settings from the inventory. This could be coded up in some `vars` file(s) in-between other Ansible settings, or using a separate file (as in your approach), and use the Ansible `lookup` feature to then include said file in the inventory as value for the appropriate `var`.

@Zempashi Do you think the above makes sense?

**Comment by Zempashi** [comment]
@NicolasT yes I do, I started a new PR (#253) to draft some code for what we envisioned

**Pull request closed without merging**
