### PR TITLE
[UI] Nodes sorting

### LINKED ISSUE #2919: Ability to sort in MetalK8s UI Nodes table
**Component**:

'ui'

**Why this is needed**:

In the same way we can sort in Volumes table, it would be great to have the ability to sort in the Nodes table

**What should be done**:

Sorting should be available for all columns:

Name: Alphanumeric sorting, case-insensitive (based on Name String only)
Roles: Alphanumeric sorting
Health: Enum sorting: Critical, Warning, Healthy, Unknown
Status: Enum sorting: Ready, NotReady, Unknown

In terms of UI, it should be equivalent to what was done in Volumes table: https://github.com/scality/metalk8s/issues/2876

**Implementation proposal** (strongly recommended):

**Test plan**:

### PR DESCRIPTION
**Pull request by alexis-ld**
**Component**:
ui, nodes

**Context**: 
We want to be able to sort the Nodes table like the Volumes table.

**Summary**:
I used the same sorting logic (leveraging react-table's sorting abilities). 
I extracted the URL sync code to its custom hook and the Table sorting components to the Common layout file to avoid code redundancy between the two views.
Update:
- Introduce hook test libray 
- Bump React version to the latest v17.0.1

**Acceptance criteria**: 
Clicking on a column header on the Nodes table sorts the data according to what is specified in #2919 .
Loading the page with a sorting specified in the URL sorts the data accordingly.

---

Closes: #2919

### CODE REVIEW

**Review by thomasdanan — DISMISSED** [review]
works well for me ...

**Review by ChengYanJin — CHANGES_REQUESTED** [review]
Smart move of `useTableSortURLSync` hook! Bravo! I suggest we add a unit test for this. 

BTW, since by default we sort the node list by health. Shouldn't we auto-select the first node base on the health? 

Thanks!

**Comment by alexis-ld** [comment]
@ChengYanJin I added tests for the custom hook as well as the Node auto-select

**Review by ChengYanJin — APPROVED** [review]
LGTM!
Thanks for introducing the hook test library and bump React to the latest version ;)

**Review by thomasdanan — APPROVED** [review]
works as expected

**Pull request merged**
