### PR TITLE
docs: Fix build

### PR DESCRIPTION
**Pull request by NicolasT**
Fixes: 926f0e6c08c423868e15c7b95752f182350c9536
See: #293
See: https://github.com/scality/metalk8s/pull/293
Fixes: 61aac384279a7d19b7e52728be8c2a6a060a1e34
See: #305
See: https://github.com/scality/metalk8s/pull/305

### CODE REVIEW

**Review by Zempashi — APPROVED** [review]

**Comment by NicolasT** [comment]
@bert-e retry

**Comment by NicolasT** [comment]
@bert-e reset

**Comment by Zempashi** [comment]
Ok to decline ?

**Comment by NicolasT** [comment]
It should be closed automagically once #324 lands :) so no need.

**Comment by Zempashi** [comment]
magic did not happen :(

**Comment by NicolasT** [comment]
@bert-e reset

**Comment by NicolasT** [comment]
Handled by #324

**Pull request closed without merging**
