### PR TITLE
ui: use the `browser` branch from `@scality/kubernetes-client-javascript`

### PR DESCRIPTION
**Pull request by NicolasT**
See: https://github.com/scality/kubernetes-client-javascript/pull/1

### CODE REVIEW

**Comment by NicolasT** [comment]
This can't be merged as-is:

- Requires https://github.com/scality/kubernetes-client-javascript/pull/1 to land
- I think we should set some tag upstream at that point (`browser-190823` or something along those lines)
- Then, update this PR to reflect that *tag* in `package.json` (and update `package-lock.json`)

**Comment by carlito-scality** [comment]
We got a problem when building UI image on local and CI. I think that the ```prepare```script was not run to build @scality/kubernetes-client-javascript
image

**Comment by NicolasT** [comment]
Yes, looking into it.

**Comment by carlito-scality** [comment]
> Yes, looking into it.

maybe linked to this issue: https://github.com/npm/npm/issues/17346

**Comment by NicolasT** [comment]
Or https://github.com/npm/npm/issues/19684, trying that now.

**Comment by NicolasT** [comment]
Likely an issue with https://docs.npmjs.com/misc/config#unsafe-perm since we run the build as `root` in the container. Testing locally...

**Comment by carlito-scality** [comment]
> Likely an issue with https://docs.npmjs.com/misc/config#unsafe-perm since we run the build as `root` in the container. Testing locally...

It works for me on local

**Comment by NicolasT** [comment]
Build fixed

**Comment by NicolasT** [comment]
Now using an upstream tag.

**Review by slaperche-scality — APPROVED** [review]

**Pull request merged**
