### PR TITLE
Storage operator

### PR DESCRIPTION
**Pull request by NicolasT**
**Component**: kubernetes, storage-operator', 'tests'... -->
**Context**: Initial implementation of the storage operator

### CODE REVIEW

**Comment by NicolasT** [comment]
The path forward:
- [ ] Create a Salt `ext-pillar` that takes `Volume` objects and represents them in the pillar of target nodes
- [ ] Create Salt state(s) to deploy such volumes
- [ ] Trigger a Salt job to deploy a volume when a `Volume` object is created, and requeue the event with a wait time. Store the Salt JID in the object status.
- [ ] Until the Salt job is done, requeue. If job no longer found, emit event and restart.
- [ ] Once done, if unsuccessful, put the `Volume` object in some error state/condition
- [ ] If successful, create the PV object
- [ ] Implement `finalizer` removal on PV when `Volume` is deleted.
- [ ] Properly handle `capacity`

TBD:
- [ ] Prefer to use block devices and let K8s handle mounting, instead of performing the mount on the host and manage it?
- [ ] Use mount options and such from `StorageClass`
- [ ] ...

**Comment by NicolasT** [comment]
How to test/develop this:

- Copy `admin.conf` to your local machine, and set `KUBECONFIG`
- Download `operator-sdk` from the release page. 0.8.1 didn't work for me, 0.8.0 did.
- Clone this repository in `$GOPATH/src/github.com/metalk8s`
- `export GO111MODULE=on`
- `cd storage-operator`
- `go mod vendor`
- `operator-sdk up local`
- `kubectl apply -f deploy/crds/storage_v1alpha1_volume_cr.yaml` and see logs in other terminal, then `kubectl delete ...`. Note: currently, the `PersistentVolume` will *not* be deleted because of a `finalizer` put in place that's not (yet) properly removed by the operator when the `Volume` is deleted. `kubectl edit pv ...` to remove the `finalizer`.

**Comment by NicolasT** [comment]
@nootal is up-to-date about this one.

**Comment by NicolasT** [comment]
FWIW, starting in (at least) K8s 1.13, `kubelet` will take care of mounting when presented a local block device for `Filesystem` use, and `mountOptions` on the PV are taken into account.

**Comment by NicolasT** [comment]
@bert-e wait

**Review by slaperche-scality — DISMISSED** [review]

**Review by slaperche-scality — DISMISSED** [review]

**Review by slaperche-scality — DISMISSED** [review]

**Comment by NicolasT** [comment]
@bert-e approve

**Review by slaperche-scality — APPROVED** [review]

**Comment by slaperche-scality** [comment]
@bert-e reset

**Comment by slaperche-scality** [comment]
@bert-e help

**Pull request merged**
