### PR TITLE
Downgrade: Remove the tty arguments from crictl exec

### PR DESCRIPTION
**Pull request by Ebaneck**
**Component**:

'downgrade', 'containers'

**Context**: 

See #1913 

**Summary**:

**Acceptance criteria**: 

---

Closes: #1913

### CODE REVIEW

**Review by slaperche-scality — DISMISSED** [review]
Should explain why we remove this option in the commit message.

**Review by TeddyAndrieux — DISMISSED** [review]

**Review by TeddyAndrieux — APPROVED** [review]
LGTM, sorry my bad

**Review by slaperche-scality — APPROVED** [review]

**Pull request merged**
