### PR TITLE
salt: Add saltenv when running highstate

### PR DESCRIPTION
**Pull request by Ebaneck**
**Component**:

'salt'

**Context**: 

Ensure we always apply highstate with correct saltenv at all times.

**Summary**:

See  #1923 

**Acceptance criteria**: 

---

Closes: #1923

### CODE REVIEW

**Review by TeddyAndrieux — DISMISSED** [review]
LGTM

**Review by slaperche-scality — COMMENTED** [review]
Missing `Closes: #1923` in the commit message :wink:

**Review by TeddyAndrieux — APPROVED** [review]

**Review by slaperche-scality — APPROVED** [review]

**Pull request merged**
