### PR TITLE
Bump doit version

### PR DESCRIPTION
**Pull request by slaperche-scality**
**Component**:

buildchain

**Context**: 

Bump `doit` version to benefits from improvements and bugfixes.

**Summary**:

- Bump `doit` version
- remove workaround in `file_tree.py`

**Acceptance criteria**: 

No regression on build.

---

Closes: #2215

### CODE REVIEW

**Comment by alexandre-allard** [comment]
Shouldn't this change target the `development/2.0` branch ?

**Comment by slaperche-scality** [comment]
> Shouldn't this change target the `development/2.0` branch ?

Doesn't bring much improvement/changes, so not sure if it's worth facing 6 builds, but I can if we want to :slightly_smiling_face:

**Review by alexandre-allard — APPROVED** [review]

**Review by ChengYanJin — APPROVED** [review]
Works as expected in my macOS!!!

**Pull request merged**
