### PR TITLE
docs: got rid of non-English word.

### PR DESCRIPTION
**Pull request by gdemonet**
**Component**: docs

**Context**: One bad word.

**Summary**: Changed "compacity" to "compactness" 

**Acceptance criteria**: Reads good, don't it? 

---

See #2297 (re-created since invalid branch name)

### CODE REVIEW

**Review by slaperche-scality — APPROVED** [review]

**Comment by wabernatScality** [comment]
@bert-e approve

**Review by wabernat — APPROVED** [review]

**Comment by wabernat** [comment]
If this is resisting the merge, I also made the same change in the "deep edit" (#2303), so you can safely abandon this PR.

**Comment by NicolasT** [comment]
@bert-e help

**Comment by NicolasT** [comment]
@bert-e bypass_build_status

**Pull request merged**
