### PR TITLE
buildchain: don't bail out when a directory already exists

### PR DESCRIPTION
**Pull request by NicolasT**

### CODE REVIEW

**Review by slaperche-scality — DISMISSED** [review]

**Comment by NicolasT** [comment]
@bert-e approve

**Comment by NicolasT** [comment]
@bert-e reset

**Comment by NicolasT** [comment]
@bert-e reset

**Review by slaperche-scality — APPROVED** [review]

**Comment by NicolasT** [comment]
@bert-e reset

**Pull request merged**
