### PR TITLE
vagrant: use ICH9 machines and `virtio` networking

### PR DESCRIPTION
**Pull request by NicolasT**
This is 2019, after all.

### CODE REVIEW

**Review by slaperche-scality — APPROVED** [review]

**Comment by NicolasT** [comment]
@slaperche-scality Would you agree if I tell BertE to ignore the CI/tests? PR has 0 impact on them.

**Comment by slaperche-scality** [comment]
> @slaperche-scality Would you agree if I tell BertE to ignore the CI/tests? PR has 0 impact on them.

Yeah sure, CI doesn't use Vagrant (so even if you did something wrong it won't be detected by it) so we can bypass it

**Comment by NicolasT** [comment]
@bert-e help

**Comment by NicolasT** [comment]
@bert-e bypass_build_status

**Comment by NicolasT** [comment]
@bert-e approve

**Comment by NicolasT** [comment]
> # Not authorized
> 
> I'm afraid I cannot do that, @NicolasT:
> 
> > @bert-e bypass_build_status
> 
> You cannot use `bypass_build_status` in your own pull request.
> 
> Please **edit** or **delete** the corresponding comment so I can move on.

Ugh @slaperche-scality pls :P

**Comment by slaperche-scality** [comment]
@bert-e bypass_build_status

**Comment by NicolasT** [comment]
@bert-e status

**Comment by NicolasT** [comment]
Ugh, @tcarmet?

**Comment by tcarmet** [comment]
@bert-e bypass_build_status

**Pull request merged**
